### ISSUE TITLE
[#08-09] 메인(검색), 게시글, 게시판, 채용공고, 기업 카드 통합 컴포넌트 개발

### ISSUE THREAD

**Issue by qjrm1430** [WeDontKnowAnything/jobAdream#20]
### Task List 

GETSPRING8230
- [x] 화면 설계
- [x] 스토리보드 설계

QJRM1430
- [x] 메인 컴포넌트 구현
- [x] 게시판 컴포넌트 구현
- [x] 게시글 컴포넌트 구현
- [x] 채용공고 통합 컴포넌트 구현
- [x] 기업 통합 컴포넌트 구현
- [x] 채용공고 단일 컴포넌트 구현
- [x] 기업 단일 컴포넌트 구현
- [x] API 연동
- [x] 단위 테스트
- [x] 전체 테스트 

### 버그 리포트

1. package.json 설치파일이 버전이 다르게 설치되는 문제 발생 -> 해당 문제로 인해 제대로 navigation이 적용이 안되는 것으로 추정
![image](https://github.com/user-attachments/assets/4358a21c-b069-409e-b648-b62043b41aa9)
해결 : 내부 프록시에서 vm.proxy?.$can 메서드를 호출하여 권한을 체크하며, 이 메서드가 존재하지 않거나 인스턴스를 가져올 수 없는 경우 기본적으로 false를 반환하기 떄문에 로그인 기능을 사용하지 않는 해당 프로젝트에선 v-if 구문을 NavGroup과 NavLink에서 제외시켜줘야했다.

- [x] 해결 여부
